//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM_API_V4
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarPurchase
    {
        public long Id { get; set; }
        public long CarID { get; set; }
        public long Buyer1ID { get; set; }
        public Nullable<long> Buyer2ID { get; set; }
        public long Seller1ID { get; set; }
        public Nullable<long> Seller2ID { get; set; }
        public Nullable<long> Witness1ID { get; set; }
        public Nullable<long> Witness2ID { get; set; }
        public System.DateTime DealDate { get; set; }
        public decimal Price { get; set; }
        public decimal BuyerCom { get; set; }
        public decimal SellerCom { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Account Account2 { get; set; }
        public virtual Account Account3 { get; set; }
        public virtual Car Car { get; set; }
        public virtual Witness Witness { get; set; }
        public virtual Witness Witness1 { get; set; }
    }
}
