//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM_API_V4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Installment
    {
        public long Id { get; set; }
        public long CarPurchaseID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime NextDueDate { get; set; }
        public System.DateTime InstallmentDate { get; set; }
    }
}
