//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM_API_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string EngineNumber { get; set; }
        public string ModelNumber { get; set; }
        public string RegistrationNumber { get; set; }
        public string Color { get; set; }
        public string Maker { get; set; }
        public string Token { get; set; }
        public bool ComputerizedNoPlate { get; set; }
        public Nullable<int> NoOfPapers { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<System.DateTime> SellDate { get; set; }
        public Nullable<decimal> AdvanceAmount { get; set; }
        public Nullable<decimal> RemainingAmount { get; set; }
        public Nullable<System.DateTime> DueDateOfRemainingAmount { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string Status { get; set; }
        public Nullable<long> OwnerOneAccountId { get; set; }
        public Nullable<long> OwnerTwoAccountId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
