//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM_API_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.CarOwners = new HashSet<CarOwner>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string EngineNumber { get; set; }
        public string ModelNumber { get; set; }
        public string RegistrationNumber { get; set; }
        public string Color { get; set; }
        public string Maker { get; set; }
        public string Token { get; set; }
        public bool ComputerizedNoPlate { get; set; }
        public Nullable<int> NoOfPapers { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string ChasisNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarOwner> CarOwners { get; set; }
    }
}
