//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM_API_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarAccount
    {
        public long Id { get; set; }
        public long CarID { get; set; }
        public long OwnerOneAccountID { get; set; }
        public Nullable<long> OwnerTwoAccountID { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
        public virtual Car Car { get; set; }
    }
}
