//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HM_API_V3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trader
    {
        public long Id { get; set; }
        public decimal Commision { get; set; }
        public string Type { get; set; }
        public long AccountID { get; set; }
    }
}
