//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.SMSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="reportRequest", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    [System.SerializableAttribute()]
    public partial class reportRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string datefromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string datetoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginId {
            get {
                return this.loginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.loginIdField, value) != true)) {
                    this.loginIdField = value;
                    this.RaisePropertyChanged("loginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword {
            get {
                return this.loginPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.loginPasswordField, value) != true)) {
                    this.loginPasswordField = value;
                    this.RaisePropertyChanged("loginPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string datefrom {
            get {
                return this.datefromField;
            }
            set {
                if ((object.ReferenceEquals(this.datefromField, value) != true)) {
                    this.datefromField = value;
                    this.RaisePropertyChanged("datefrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string dateto {
            get {
                return this.datetoField;
            }
            set {
                if ((object.ReferenceEquals(this.datetoField, value) != true)) {
                    this.datetoField = value;
                    this.RaisePropertyChanged("dateto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="reportResponse", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    [System.SerializableAttribute()]
    public partial class reportResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaskingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SentDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string STATUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Masking {
            get {
                return this.MaskingField;
            }
            set {
                if ((object.ReferenceEquals(this.MaskingField, value) != true)) {
                    this.MaskingField = value;
                    this.RaisePropertyChanged("Masking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string SentDate {
            get {
                return this.SentDateField;
            }
            set {
                if ((object.ReferenceEquals(this.SentDateField, value) != true)) {
                    this.SentDateField = value;
                    this.RaisePropertyChanged("SentDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string STATUS {
            get {
                return this.STATUSField;
            }
            set {
                if ((object.ReferenceEquals(this.STATUSField, value) != true)) {
                    this.STATUSField = value;
                    this.RaisePropertyChanged("STATUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampaignsResquest", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    [System.SerializableAttribute()]
    public partial class CampaignsResquest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginId {
            get {
                return this.loginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.loginIdField, value) != true)) {
                    this.loginIdField = value;
                    this.RaisePropertyChanged("loginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword {
            get {
                return this.loginPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.loginPasswordField, value) != true)) {
                    this.loginPasswordField = value;
                    this.RaisePropertyChanged("loginPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampaignsResponse", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    [System.SerializableAttribute()]
    public partial class CampaignsResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GroupNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupName {
            get {
                return this.GroupNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GroupNameField, value) != true)) {
                    this.GroupNameField = value;
                    this.RaisePropertyChanged("GroupName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuickSMSResquest", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    [System.SerializableAttribute()]
    public partial class QuickSMSResquest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortCodePreferedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginId {
            get {
                return this.loginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.loginIdField, value) != true)) {
                    this.loginIdField = value;
                    this.RaisePropertyChanged("loginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword {
            get {
                return this.loginPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.loginPasswordField, value) != true)) {
                    this.loginPasswordField = value;
                    this.RaisePropertyChanged("loginPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Mask {
            get {
                return this.MaskField;
            }
            set {
                if ((object.ReferenceEquals(this.MaskField, value) != true)) {
                    this.MaskField = value;
                    this.RaisePropertyChanged("Mask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string UniCode {
            get {
                return this.UniCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UniCodeField, value) != true)) {
                    this.UniCodeField = value;
                    this.RaisePropertyChanged("UniCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ShortCodePrefered {
            get {
                return this.ShortCodePreferedField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortCodePreferedField, value) != true)) {
                    this.ShortCodePreferedField = value;
                    this.RaisePropertyChanged("ShortCodePrefered");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CounterRequest", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    [System.SerializableAttribute()]
    public partial class CounterRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginId {
            get {
                return this.loginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.loginIdField, value) != true)) {
                    this.loginIdField = value;
                    this.RaisePropertyChanged("loginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword {
            get {
                return this.loginPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.loginPasswordField, value) != true)) {
                    this.loginPasswordField = value;
                    this.RaisePropertyChanged("loginPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CounterResponse", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    [System.SerializableAttribute()]
    public partial class CounterResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Total_BalanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Total_BroadcastedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Total_SuccessfulField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Total_FailedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_MasksField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total_Balance {
            get {
                return this.Total_BalanceField;
            }
            set {
                if ((object.ReferenceEquals(this.Total_BalanceField, value) != true)) {
                    this.Total_BalanceField = value;
                    this.RaisePropertyChanged("Total_Balance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total_Broadcasted {
            get {
                return this.Total_BroadcastedField;
            }
            set {
                if ((object.ReferenceEquals(this.Total_BroadcastedField, value) != true)) {
                    this.Total_BroadcastedField = value;
                    this.RaisePropertyChanged("Total_Broadcasted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total_Successful {
            get {
                return this.Total_SuccessfulField;
            }
            set {
                if ((object.ReferenceEquals(this.Total_SuccessfulField, value) != true)) {
                    this.Total_SuccessfulField = value;
                    this.RaisePropertyChanged("Total_Successful");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Total_Failed {
            get {
                return this.Total_FailedField;
            }
            set {
                if ((object.ReferenceEquals(this.Total_FailedField, value) != true)) {
                    this.Total_FailedField = value;
                    this.RaisePropertyChanged("Total_Failed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string User_Masks {
            get {
                return this.User_MasksField;
            }
            set {
                if ((object.ReferenceEquals(this.User_MasksField, value) != true)) {
                    this.User_MasksField = value;
                    this.RaisePropertyChanged("User_Masks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BulkSMSResquest", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    [System.SerializableAttribute()]
    public partial class BulkSMSResquest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampaignNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UniCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SMS.SMSService.numbersList[] lstNLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampaignDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortCodePreferedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginId {
            get {
                return this.loginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.loginIdField, value) != true)) {
                    this.loginIdField = value;
                    this.RaisePropertyChanged("loginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword {
            get {
                return this.loginPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.loginPasswordField, value) != true)) {
                    this.loginPasswordField = value;
                    this.RaisePropertyChanged("loginPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string CampaignName {
            get {
                return this.CampaignNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CampaignNameField, value) != true)) {
                    this.CampaignNameField = value;
                    this.RaisePropertyChanged("CampaignName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Mask {
            get {
                return this.MaskField;
            }
            set {
                if ((object.ReferenceEquals(this.MaskField, value) != true)) {
                    this.MaskField = value;
                    this.RaisePropertyChanged("Mask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string UniCode {
            get {
                return this.UniCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UniCodeField, value) != true)) {
                    this.UniCodeField = value;
                    this.RaisePropertyChanged("UniCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public SMS.SMSService.numbersList[] lstNL {
            get {
                return this.lstNLField;
            }
            set {
                if ((object.ReferenceEquals(this.lstNLField, value) != true)) {
                    this.lstNLField = value;
                    this.RaisePropertyChanged("lstNL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string CampaignDate {
            get {
                return this.CampaignDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CampaignDateField, value) != true)) {
                    this.CampaignDateField = value;
                    this.RaisePropertyChanged("CampaignDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string ShortCodePrefered {
            get {
                return this.ShortCodePreferedField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortCodePreferedField, value) != true)) {
                    this.ShortCodePreferedField = value;
                    this.RaisePropertyChanged("ShortCodePrefered");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="numbersList", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    [System.SerializableAttribute()]
    public partial class numbersList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DynamicSMSRequest", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    [System.SerializableAttribute()]
    public partial class DynamicSMSRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MaskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SMS.SMSService.DynamicList[] lstNLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CampaignDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortCodePreferedField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginId {
            get {
                return this.loginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.loginIdField, value) != true)) {
                    this.loginIdField = value;
                    this.RaisePropertyChanged("loginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword {
            get {
                return this.loginPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.loginPasswordField, value) != true)) {
                    this.loginPasswordField = value;
                    this.RaisePropertyChanged("loginPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Mask {
            get {
                return this.MaskField;
            }
            set {
                if ((object.ReferenceEquals(this.MaskField, value) != true)) {
                    this.MaskField = value;
                    this.RaisePropertyChanged("Mask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public SMS.SMSService.DynamicList[] lstNL {
            get {
                return this.lstNLField;
            }
            set {
                if ((object.ReferenceEquals(this.lstNLField, value) != true)) {
                    this.lstNLField = value;
                    this.RaisePropertyChanged("lstNL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string CampaignDate {
            get {
                return this.CampaignDateField;
            }
            set {
                if ((object.ReferenceEquals(this.CampaignDateField, value) != true)) {
                    this.CampaignDateField = value;
                    this.RaisePropertyChanged("CampaignDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string ShortCodePrefered {
            get {
                return this.ShortCodePreferedField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortCodePreferedField, value) != true)) {
                    this.ShortCodePreferedField = value;
                    this.RaisePropertyChanged("ShortCodePrefered");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DynamicList", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    [System.SerializableAttribute()]
    public partial class DynamicList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Var1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Var2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Var3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Var4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Var5Field;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Var1 {
            get {
                return this.Var1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Var1Field, value) != true)) {
                    this.Var1Field = value;
                    this.RaisePropertyChanged("Var1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Var2 {
            get {
                return this.Var2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Var2Field, value) != true)) {
                    this.Var2Field = value;
                    this.RaisePropertyChanged("Var2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Var3 {
            get {
                return this.Var3Field;
            }
            set {
                if ((object.ReferenceEquals(this.Var3Field, value) != true)) {
                    this.Var3Field = value;
                    this.RaisePropertyChanged("Var3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Var4 {
            get {
                return this.Var4Field;
            }
            set {
                if ((object.ReferenceEquals(this.Var4Field, value) != true)) {
                    this.Var4Field = value;
                    this.RaisePropertyChanged("Var4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Var5 {
            get {
                return this.Var5Field;
            }
            set {
                if ((object.ReferenceEquals(this.Var5Field, value) != true)) {
                    this.Var5Field = value;
                    this.RaisePropertyChanged("Var5");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InboxRequest", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    [System.SerializableAttribute()]
    public partial class InboxRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string loginPasswordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginId {
            get {
                return this.loginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.loginIdField, value) != true)) {
                    this.loginIdField = value;
                    this.RaisePropertyChanged("loginId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string loginPassword {
            get {
                return this.loginPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.loginPasswordField, value) != true)) {
                    this.loginPasswordField = value;
                    this.RaisePropertyChanged("loginPassword");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InboxResponse", Namespace="http://schemas.datacontract.org/2004/07/CBSCustomerAPI")]
    [System.SerializableAttribute()]
    public partial class InboxResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReplyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReplyDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mobile {
            get {
                return this.MobileField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileField, value) != true)) {
                    this.MobileField = value;
                    this.RaisePropertyChanged("Mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reply {
            get {
                return this.ReplyField;
            }
            set {
                if ((object.ReferenceEquals(this.ReplyField, value) != true)) {
                    this.ReplyField = value;
                    this.RaisePropertyChanged("Reply");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReplyDate {
            get {
                return this.ReplyDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReplyDateField, value) != true)) {
                    this.ReplyDateField = value;
                    this.RaisePropertyChanged("ReplyDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSService.ICorporateCBS")]
    public interface ICorporateCBS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/GetReports", ReplyAction="http://tempuri.org/ICorporateCBS/GetReportsResponse")]
        SMS.SMSService.reportResponse[] GetReports(SMS.SMSService.reportRequest objReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/GetReports", ReplyAction="http://tempuri.org/ICorporateCBS/GetReportsResponse")]
        System.Threading.Tasks.Task<SMS.SMSService.reportResponse[]> GetReportsAsync(SMS.SMSService.reportRequest objReport);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/GetCampaigns", ReplyAction="http://tempuri.org/ICorporateCBS/GetCampaignsResponse")]
        SMS.SMSService.CampaignsResponse[] GetCampaigns(SMS.SMSService.CampaignsResquest objCampaigns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/GetCampaigns", ReplyAction="http://tempuri.org/ICorporateCBS/GetCampaignsResponse")]
        System.Threading.Tasks.Task<SMS.SMSService.CampaignsResponse[]> GetCampaignsAsync(SMS.SMSService.CampaignsResquest objCampaigns);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/QuickSMS", ReplyAction="http://tempuri.org/ICorporateCBS/QuickSMSResponse")]
        string QuickSMS(SMS.SMSService.QuickSMSResquest obj_QuickSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/QuickSMS", ReplyAction="http://tempuri.org/ICorporateCBS/QuickSMSResponse")]
        System.Threading.Tasks.Task<string> QuickSMSAsync(SMS.SMSService.QuickSMSResquest obj_QuickSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/GetAccountSummary", ReplyAction="http://tempuri.org/ICorporateCBS/GetAccountSummaryResponse")]
        SMS.SMSService.CounterResponse[] GetAccountSummary(SMS.SMSService.CounterRequest obj_GetAccountSummary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/GetAccountSummary", ReplyAction="http://tempuri.org/ICorporateCBS/GetAccountSummaryResponse")]
        System.Threading.Tasks.Task<SMS.SMSService.CounterResponse[]> GetAccountSummaryAsync(SMS.SMSService.CounterRequest obj_GetAccountSummary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/BulkSMS", ReplyAction="http://tempuri.org/ICorporateCBS/BulkSMSResponse")]
        string BulkSMS(SMS.SMSService.BulkSMSResquest obj_BulkSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/BulkSMS", ReplyAction="http://tempuri.org/ICorporateCBS/BulkSMSResponse")]
        System.Threading.Tasks.Task<string> BulkSMSAsync(SMS.SMSService.BulkSMSResquest obj_BulkSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/DynamicSMS", ReplyAction="http://tempuri.org/ICorporateCBS/DynamicSMSResponse")]
        string DynamicSMS(SMS.SMSService.DynamicSMSRequest obj_DynamicSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/DynamicSMS", ReplyAction="http://tempuri.org/ICorporateCBS/DynamicSMSResponse")]
        System.Threading.Tasks.Task<string> DynamicSMSAsync(SMS.SMSService.DynamicSMSRequest obj_DynamicSMS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/GetInbox", ReplyAction="http://tempuri.org/ICorporateCBS/GetInboxResponse")]
        SMS.SMSService.InboxResponse[] GetInbox(SMS.SMSService.InboxRequest objInbox);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICorporateCBS/GetInbox", ReplyAction="http://tempuri.org/ICorporateCBS/GetInboxResponse")]
        System.Threading.Tasks.Task<SMS.SMSService.InboxResponse[]> GetInboxAsync(SMS.SMSService.InboxRequest objInbox);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICorporateCBSChannel : SMS.SMSService.ICorporateCBS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CorporateCBSClient : System.ServiceModel.ClientBase<SMS.SMSService.ICorporateCBS>, SMS.SMSService.ICorporateCBS {
        
        public CorporateCBSClient() {
        }
        
        public CorporateCBSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CorporateCBSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorporateCBSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CorporateCBSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SMS.SMSService.reportResponse[] GetReports(SMS.SMSService.reportRequest objReport) {
            return base.Channel.GetReports(objReport);
        }
        
        public System.Threading.Tasks.Task<SMS.SMSService.reportResponse[]> GetReportsAsync(SMS.SMSService.reportRequest objReport) {
            return base.Channel.GetReportsAsync(objReport);
        }
        
        public SMS.SMSService.CampaignsResponse[] GetCampaigns(SMS.SMSService.CampaignsResquest objCampaigns) {
            return base.Channel.GetCampaigns(objCampaigns);
        }
        
        public System.Threading.Tasks.Task<SMS.SMSService.CampaignsResponse[]> GetCampaignsAsync(SMS.SMSService.CampaignsResquest objCampaigns) {
            return base.Channel.GetCampaignsAsync(objCampaigns);
        }
        
        public string QuickSMS(SMS.SMSService.QuickSMSResquest obj_QuickSMS) {
            return base.Channel.QuickSMS(obj_QuickSMS);
        }
        
        public System.Threading.Tasks.Task<string> QuickSMSAsync(SMS.SMSService.QuickSMSResquest obj_QuickSMS) {
            return base.Channel.QuickSMSAsync(obj_QuickSMS);
        }
        
        public SMS.SMSService.CounterResponse[] GetAccountSummary(SMS.SMSService.CounterRequest obj_GetAccountSummary) {
            return base.Channel.GetAccountSummary(obj_GetAccountSummary);
        }
        
        public System.Threading.Tasks.Task<SMS.SMSService.CounterResponse[]> GetAccountSummaryAsync(SMS.SMSService.CounterRequest obj_GetAccountSummary) {
            return base.Channel.GetAccountSummaryAsync(obj_GetAccountSummary);
        }
        
        public string BulkSMS(SMS.SMSService.BulkSMSResquest obj_BulkSMS) {
            return base.Channel.BulkSMS(obj_BulkSMS);
        }
        
        public System.Threading.Tasks.Task<string> BulkSMSAsync(SMS.SMSService.BulkSMSResquest obj_BulkSMS) {
            return base.Channel.BulkSMSAsync(obj_BulkSMS);
        }
        
        public string DynamicSMS(SMS.SMSService.DynamicSMSRequest obj_DynamicSMS) {
            return base.Channel.DynamicSMS(obj_DynamicSMS);
        }
        
        public System.Threading.Tasks.Task<string> DynamicSMSAsync(SMS.SMSService.DynamicSMSRequest obj_DynamicSMS) {
            return base.Channel.DynamicSMSAsync(obj_DynamicSMS);
        }
        
        public SMS.SMSService.InboxResponse[] GetInbox(SMS.SMSService.InboxRequest objInbox) {
            return base.Channel.GetInbox(objInbox);
        }
        
        public System.Threading.Tasks.Task<SMS.SMSService.InboxResponse[]> GetInboxAsync(SMS.SMSService.InboxRequest objInbox) {
            return base.Channel.GetInboxAsync(objInbox);
        }
    }
}
